//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vostok.ZooKeeper.LocalEnsemble.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vostok.ZooKeeper.LocalEnsemble.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] jarjar_1_4 {
            get {
                object obj = ResourceManager.GetObject("jarjar_1_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] jline_0_9_94 {
            get {
                object obj = ResourceManager.GetObject("jline_0_9_94", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] log4j_1_2_15 {
            get {
                object obj = ResourceManager.GetObject("log4j_1_2_15", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] netty_3_2_2_Final {
            get {
                object obj = ResourceManager.GetObject("netty_3_2_2_Final", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] slf4j_api_1_6_1 {
            get {
                object obj = ResourceManager.GetObject("slf4j_api_1_6_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] slf4j_log4j12_1_6_1 {
            get {
                object obj = ResourceManager.GetObject("slf4j_log4j12_1_6_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///REM Licensed to the Apache Software Foundation (ASF) under one or more
        ///REM contributor license agreements.  See the NOTICE file distributed with
        ///REM this work for additional information regarding copyright ownership.
        ///REM The ASF licenses this file to You under the Apache License, Version 2.0
        ///REM (the &quot;License&quot;); you may not use this file except in compliance with
        ///REM the License.  You may obtain a copy of the License at
        ///REM
        ///REM     http://www.apache.org/licenses/LICENSE-2.0
        ///REM
        ///REM Unles [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string zkEnv {
            get {
                return ResourceManager.GetString("zkEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///REM Licensed to the Apache Software Foundation (ASF) under one or more
        ///REM contributor license agreements.  See the NOTICE file distributed with
        ///REM this work for additional information regarding copyright ownership.
        ///REM The ASF licenses this file to You under the Apache License, Version 2.0
        ///REM (the &quot;License&quot;); you may not use this file except in compliance with
        ///REM the License.  You may obtain a copy of the License at
        ///REM
        ///REM     http://www.apache.org/licenses/LICENSE-2.0
        ///REM
        ///REM Unles [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string zkServer {
            get {
                return ResourceManager.GetString("zkServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] zookeeper_3_4_5 {
            get {
                object obj = ResourceManager.GetObject("zookeeper_3_4_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
